### ISSUE TITLE
code isnt working 

### ISSUE THREAD

**Issue by Chummy2** [TreborNamor/Agressive-Store-Bots#34]
does anyone know how to fix this error? 
![Screenshot 2021-04-17 031712](https://user-images.githubusercontent.com/82701125/115106669-c1470800-9f2b-11eb-8263-e5b4b80942aa.png)

**Comment by KingFascinate** [comment]
Try to do the pip installs. That should fix it

**Comment by Chummy2** [comment]
It still doesnt work

**Comment by TreborNamor** [comment]
Can you take a screenshot of line 63? I'll take a look

**Comment by Chummy2** [comment]
![343508E4-98B3-431B-8B56-1A8E3824BEE0](https://user-images.githubusercontent.com/82701125/115287388-d4b5c700-a115-11eb-826c-0fee622e0163.jpeg)

**Comment by TreborNamor** [comment]
I'm not sure why you had put line 63 up there but I would just delete it. You need to edit line 67 like the example below. It's pretty much just copying and pasting your line 63 into line 67 to look like the bottom example.

 r'c:\Users\18125\AppData\Roaming\Mozilla\Firefox\Profiles\iryawpfe.default-release'
