### ISSUE TITLE
Best Buy URL

### ISSUE THREAD

**Issue by pyrokidd89** [TreborNamor/Agressive-Store-Bots#41]
So I am confused on which type of URL to use. The read me page seems to contradict the instructions in the best buy bot script.

Do I use a search page URL or a direct product URL?

Search URL example:
`https://www.bestbuy.com/site/searchpage.jsp?_dyncharset=UTF-8&id=pcat17071&iht=y&keys=keys&ks=960&list=n&qp=currentprice_facet%3DPrice~Less%20than%20%2425&sc=Global&st=hdmi&type=page&usc=All%20Categories
`
Direct product URL example:
`https://www.bestbuy.com/site/sony-playstation-5-console/6426149.p?skuId=6426149`

**Comment by TreborNamor** [comment]
Hey thanks for pointing that out. I'll go ahead and fix that. It used to be
product page url but now I updated to direct product url.

Direct product URL example:
https://www.bestbuy.com/site/sony-playstation-5-console/6426149.p?skuId=6426149
